# Generated by Django 5.0.6 on 2024-07-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_coursemaster_exammaster_papermaster_semmaster_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BatchMasterModel',
            new_name='BatchMaster',
        ),
    ]
