# Generated by Django 5.0.7 on 2024-07-13 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_batchmastermodel_batchmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('batchno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.batchmaster')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.coursemaster')),
                ('examtype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.exammaster')),
                ('papercode', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.papermaster')),
                ('sem', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.semmaster')),
                ('studentname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.studentmaster')),
            ],
        ),
    ]
