# Generated by Django 5.0.7 on 2024-07-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_batchmaster_batchid_alter_batchmaster_batchno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmaster',
            name='batchid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='batchmaster',
            name='batchno',
            field=models.IntegerField(default=0),
        ),
    ]
