# Generated by Django 5.0.7 on 2024-07-14 13:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_transaction_studentname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Only alphabetic characters are allowed.', regex='^[a-zA-Z]*$')])),
                ('studentregno', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter only integer.', regex='^[0-9]+$')])),
                ('batchid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.batchmaster')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.coursemaster')),
                ('sem', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.semmaster')),
            ],
        ),
    ]
